MauldinEconomics/mautic

app/bundles/CoreBundle/Model/VariantModelTrait.php
**Type:** Bug fix 
**Description:** Calling missing method for emails setVariantSentCount when processing variant for landing pages.
**Fix:** Ignore the call when processing landing pages
=> Testing multiple variants for landing pages (RR15)

plugins/MauticMauldinFiltersBundle/Config/config.php, plugins/MauticMauldinFiltersBundle/EventListener/LeadSubscriber.php, plugins/MauticMauldinFiltersBundle/MauticMauldinFiltersBundle.php, plugins/MauticMauldinFiltersBundle/Translations/en_US/messages.ini
Adds the _MauticMauldinFiltersBundle_ plugin.
Depends on #17. Replaces #12.
=> Add new Filters plugin (RR22)

composer.json, composer.lock, plugins/MauticMauldinCSIBundle/Config/config.php, plugins/MauticMauldinCSIBundle/Model/CSIModel.php, plugins/MauticMauldinEmailScalabilityBundle/Config/config.php, plugins/MauticMauldinEmailScalabilityBundle/Transport/RabbitmqTransportQueue.php
Note that this adds a new dependency.
=> Lazy load rabbitmq to avoid unnecessary connections

composer.json, composer.lock, plugins/MauticMauldinEmailScalabilityBundle/Config/config.php, plugins/MauticMauldinEmailScalabilityBundle/Swiftmailer/Transport/RabbitmqTransport.php
This requires some configuration changes, which are here: https://github.com/MauldinEconomics/csi-unicorn/pull/51
=> Allow sendgrid API instead of SMTP

plugins/MauticMauldinCSIBundle/Command/ProcessCSIOptListCommand.php
| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| Related user documentation PR URL | no
| Related developer documentation PR URL | https://github.com/MauldinEconomics/csi-unicorn/pull/61
| Issues addressed (#s or URLs) | no
| BC breaks? | no
| Deprecations? | no
[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )
This fixes a bug discovered in production due to the extra API authentication needed there.
1. Add a contact to a CSI list in production mautic
2. Trigger `app/console mautic:csi:list:update`
=> Csi api fix

apc-stat.php, index.php
This is *optional*, if you want to have a status page for the APC cache.
Depends on #38
=> Add apc status page

index.php
Depends on: https://github.com/MauldinEconomics/csi-unicorn/pull/66
=> Enable APC

app/bundles/CoreBundle/Model/VariantModelTrait.php, plugins/MauticMauldinEmailScalabilityBundle/Command/BroadcastConsumeCommand.php, plugins/MauticMauldinEmailScalabilityBundle/MessageQueue/QueueProcessingCommand.php, plugins/MauticMauldinEmailScalabilityBundle/Model/QueuedEmailModel.php
This should fix the errors in the broadcast command.
=> One queue for each broadcast

app/bundles/CoreBundle/Model/VariantModelTrait.php, app/bundles/EmailBundle/Controller/EmailController.php, app/bundles/EmailBundle/Views/Email/details.html.php
Depends on #53 
Depends on https://github.com/MauldinEconomics/csi-unicorn/pull/93 (requires a new table)
=> Record ab-test results when rolling out and improve email stats

plugins/MauticMauldinCSIBundle/Translations/en_US/messages.ini
=> Add missing translation

app/bundles/EmailBundle/Controller/PublicController.php, app/bundles/EmailBundle/EventListener/PageSubscriber.php, app/bundles/EmailBundle/Model/EmailModel.php, plugins/MauticMauldinEmailScalabilityBundle/Command/ProcessEmailHitCommand.php, plugins/MauticMauldinEmailScalabilityBundle/MessageQueue/QueueRequestHelper.php, plugins/MauticMauldinEmailScalabilityBundle/Model/QueuedEmailModel.php
Depends on https://github.com/MauldinEconomics/csi-unicorn/pull/109
This is the route configuration for the email tracking pixel.
```
'mautic_email_tracker' => [
'path'       => '/email/{idHash}.gif',
'controller' => 'MauticEmailBundle:Public:trackingImage',
],
```
=> Assynchronous email hit handling

plugins/MauticMauldinCSIBundle/Command/ProcessCSIListOptCommand.php, plugins/MauticMauldinCSIBundle/Command/ProcessCSISurveyResultCommand.php, plugins/MauticMauldinCSIBundle/Model/SETRequestModel.php, plugins/MauticMauldinEmailScalabilityBundle/Command/ProcessEmailQueueCommand.php, plugins/MauticMauldinEmailScalabilityBundle/Command/UpdateLeadListsCommand.php, plugins/MauticMauldinEmailScalabilityBundle/Model/EventModelExtended.php, plugins/MauticMauldinEmailScalabilityBundle/Model/QueuedEmailModel.php, plugins/MauticMauldinEmailScalabilityBundle/Swiftmailer/Transport/RabbitmqTransport.php
Depends on https://github.com/MauldinEconomics/csi-unicorn/pull/116
=> Scalable Email helper

plugins/MauticMauldinEmailScalabilityBundle/Command/UpdateLeadListsCommand.php
Some additional logging to help debugging.
=> Help debugging segments not updating

app/bundles/LeadBundle/Model/LeadModel.php, app/bundles/PageBundle/Config/config.php, app/bundles/PageBundle/Controller/PublicController.php, app/bundles/PageBundle/Model/PageModel.php, plugins/MauticMauldinEmailScalabilityBundle/Command/ProcessPageHitCommand.php
Depends on https://github.com/MauldinEconomics/csi-unicorn/pull/136
=> Use queue to handle page hits

plugins/MauticMauldinEmailScalabilityBundle/Model/EventModelExtended.php
This patch allows root events that were added after the campaign is published to be executed. 
Instead of passing only the set of leads to be processed. Now we put on the queue also the events to be processed. Ignoring the ones that were already processed.
There is also some improvement on when the queue is created. Doing it only if there is events to be processed.
=> Improve behavior of starting events processing

plugins/MauticMauldinCSIBundle/Command/ProcessCSISurveyResultCommand.php
=> Add csi_env to survey call

app/bundles/PageBundle/Model/PageModel.php
=> Fix lead recovery in page hit handling

plugins/MauticMauldinEmailScalabilityBundle/Command/ProcessEmailQueueCommand.php, plugins/MauticMauldinEmailScalabilityBundle/Model/QueuedEmailModel.php, plugins/MauticMauldinEmailScalabilityBundle/Swiftmailer/Transport/RabbitmqTransport.php
The category is a JSON object (encoded as string) containing the fields:
- campaign code (from the Mautic Category)
- subject
- send date
- lead id
- `mautic: true`
=> Add sendgrid categories to mautic emails

app/bundles/FormBundle/Assets/html/grecaptcha_form_field.html, nbproject/project.properties, nbproject/project.xml
| Q  | A
| --- | ---
| Bug fix? | *
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 
[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )
JS code updated to hande both Mautic and EE forms
1. 
2. 
1. Check if Mautic form functions as it should in DEV env
2. 
1. 
2. 
1. 
2.
=> Update Recaptcha js code to handle mautic and EE forms

app/bundles/FormBundle/Assets/html/grecaptcha_form_field.html, nbproject/project.properties, nbproject/project.xml
updates js to not have comment
=> Update recaptcha js code

app/bundles/FormBundle/Assets/html/grecaptcha_form_field.html
| Q  | A
| --- | ---
| Bug fix? |  Yes
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 
[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )
Updates the execution of the explicitly supplied ajax handling callback function for non mautic forms.
1. The ajax callback won't execute for EE forms. 
2. 
1. 
2. 
1. 
2. 
1. 
2.
=> Update ajax callback execution code

plugins/MauticMauldinCSIBundle/Config/config.php, plugins/MauticMauldinCSIBundle/Model/CSIListModel.php
=> does Dependency Injection for LeadAffiliateModel

composer.lock
=> updates MauticMauldinLeadAffiliateBundle plugin

plugins/MauticMauldinCSIBundle/Model/CSIListModel.php
| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 
[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )
1. 
2. 
1. 
2. 
1. 
2. 
1. 
2.
=> fixes null given error by using $this->LeadAffiliateModel

composer.lock
=> update upstream plugin requirement

app/bundles/CampaignBundle/Executioner/Scheduler/EventScheduler.php, app/bundles/CampaignBundle/Executioner/Scheduler/Mode/Interval.php
(cherry picked from commit f2a8c321fe4bb1d40d660a641108ae4fc0759563)
=> Prevent interval from doubling the expected scheduled time

app/bundles/LeadBundle/Tests/EventListener/SegmentReportSubscriberTest.php, app/bundles/ReportBundle/Builder/MauticReportBuilder.php, app/bundles/ReportBundle/Entity/Report.php, app/bundles/ReportBundle/Event/ReportGeneratorEvent.php
This branch contains cherry-picked commits to "Fix report order by and group by for artificial columns".
=> Fix report order

app/bundles/QueueBundle/Queue/QueueService.php
Temporary fix for blank message crashing
=> REJECT blank messages from queue

app/bundles/LeadBundle/Tracker/ContactTracker.php
| Q  | A
| --- | ---
| Bug fix? |  Y
| New feature? | 
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) |  #148 
| BC breaks? | 
| Deprecations? | 
Resolves #148 
1. Check logs for exception
1.  visit `/test` endpoint and get a _not 500_ response.
=> Require Lead ID for ContactTracker to updateLastActive
